### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by ndq880815** [nahojkap/jahspotify#5]
How to make an Android APP based on API modules? 
I created an Android project in Eclipse and  build user library with jahspotify-native-jar-0.0.1-SNAPSHOT.jar(including libJahSpotify.so) and jahspotify-api-0.0.1-SNAPSHOT.jar. However, it seems doesnt work. So could you give little example of using the API modules.

**Comment by nahojkap** [comment]
I think you would have to give me a little more to work with here in order to help - what do you mean it doesn't work?   

Btw, did you create Makefiles for Android (for the native parts?)  As it stands, the Jah'Spotify only works on Linux and Windows, which is the reason I ask.

**Comment by ndq880815** [comment]
Well, I think you have already hit the point. LogCat(pasted below) shows the problems in Native Method.
Does it mean that the JNI part(native method) must be compiled first with NDK (create Makefiles)? then API modules would work after loading the so file.

```
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    JahSpotify js = JahSpotifyImpl.getInstance();         //source not found
    js.login("name", "password");

    setContentView(R.layout.activity_main);
}
```

11-10 14:10:36.316: E/AndroidRuntime(587):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.app.ActivityThread.access$2300(ActivityThread.java:125)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.os.Looper.loop(Looper.java:123)
11-10 14:10:36.316: E/AndroidRuntime(587):  at android.app.ActivityThread.main(ActivityThread.java:4627)
11-10 14:10:36.316: E/AndroidRuntime(587):  at java.lang.reflect.Method.invokeNative(Native Method)
11-10 14:10:36.316: E/AndroidRuntime(587):  at java.lang.reflect.Method.invoke(Method.java:521)
11-10 14:10:36.316: E/AndroidRuntime(587):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
11-10 14:10:36.316: E/AndroidRuntime(587):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
11-10 14:10:36.316: E/AndroidRuntime(587):  at dalvik.system.NativeStart.main(Native Method)

**Comment by nahojkap** [comment]
In theory - I can't guarantee that all code will all work cleanly on Android - not targeted that platform.  If you get to the point where it all builds and works, feel free to send me a pull request and i will consider it for inclusion in the master though.

Reason it is not targeted is simple, Jah'Spotify was more aimed to be a remote controlled version that you can stack on top of the rest of your audio equipment - mostly running on Linux/WIndows OS.  I have it very nicely integrated into a Ubuntu desktop version running on a Atom/Mini ITX solution (with WIFI) Very handy at parties ;)
