### ISSUE TITLE
Installation hints

### ISSUE THREAD

**Issue by karlwettin** [nahojkap/jahspotify#6]
I just mvn installed on a clean ubuntu-server 12.04.

First I hit troubles with the jaway-andoroid plugin. Not sure what's up there, but it was looking for 3.4.0, is that due to the missing version in the second definition of the plugin in android/pom? I tried setting it manually and then it said it could not find 3.0.0-relase13 or what ever the defined version in the first definition is that I used. I just gave up and deleted the module since I don't use it.

And then I hit this in nave:

/home/kalle/jahspotify/native/src/main/native/inc/JNIHelpers.h:1:17: fatal error: jni.h: No such file or directory

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/ 

This is in no way project dependent but it still took me 15 minutes to figure that one out. : )

Also got this:

/home/kalle/jahspotify/native/src/main/native/src/openal-audio.c:28:19: fatal error: AL/al.h: No such file or directory

Not a big deal, I simply apt-get install libopenal-dev, but perhaps you should point out that dependency in the install notes of README.

**Comment by karlwettin** [comment]
You could also link to https://developer.spotify.com/technologies/libspotify/ rather than https://developer.spotify.com/

And make a note of that libspotify is available in several package managers, especially homebrew for os x since there is no good simple way to install it using their own os x distribution.

**Comment by nahojkap** [comment]
Thanks for the very valid points - will update the doc.

**Comment by nahojkap** [comment]
Latest readme updated with the comments you made - thanks
